# Generated by Django 4.1.7 on 2023-03-05 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_feeding'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feeding',
        ),
    ]
